---
# handlers file for the main docker tasks file

- name: restart docker-ce
  systemd:
    name: docker-ce 
    state: restarted


- name: start_docker
  systemd:
    name: docker
    state: started
    enabled: yes