---
# This file includes relevant tasks to assure Docker is installed, up and running on either Ubuntu or CentOS

- name: Uninstall old Docker versions | Ubuntu
  apt:
    name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
    state: absent
    force: yes
  when: 
    - ansible_facts['distribution'] == "Ubuntu"


- name: Pre-installations for Docker repository | Ubuntu
  apt:
    name: ['apt-transport-https','ca-certificates','curl','software-properties-common','gnupg-agent', 'python3-pip']
    update_cache: yes
  when: 
    - ansible_facts['distribution'] == "Ubuntu"


- name: Pre-installations for Docker repository | RedHat
  yum:
    name: yum-utils
    state: latest
  when: 
    - ansible_facts['distribution'] == "RedHat"
  

- name: Add Docker GPG key | Ubuntu
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: 
    - ansible_facts['distribution'] == "Ubuntu"


- name: Add Docker repository | Ubuntu
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
    filename: docker
  when: 
    - ansible_facts['distribution'] == "Ubuntu"


- name: Add Docker repository | RedHat
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo  
  when: 
    - ansible_facts['distribution'] == "RedHat"


- name: Install docker-ce | Ubuntu
  apt:
    name: ['docker-ce','docker-ce-cli','containerd.io']
    update_cache: yes
  notify:
  - restart docker-ce
  when: 
    - ansible_facts['distribution'] == "Ubuntu"


- name: Install docker-ce | RedHat
  package:
    name: docker-ce
    state: latest
  notify: start_docker
  when: 
    - ansible_facts['distribution'] == "RedHat"


- name: start docker | RedHat
  systemd:
    name: docker
    state: started
    enabled: yes
  when: 
    - ansible_facts['distribution'] == "RedHat"


- name: Add user ubuntu to docker group | Ubuntu
  user:
    name: ubuntu
    group: docker
  when: 
    - ansible_facts['distribution'] == "Ubuntu"


- name: Add user ec2-user to docker group | RedHat
  user:
    name: ec2-user
    group: docker
  when: 
    - ansible_facts['distribution'] == "RedHat"
  

- name: Install docker-py for docker container plugin | Ubuntu
  pip:
    name: docker-py
    state: present
  when: 
   - ansible_facts['distribution'] == "Ubuntu"


- name: Install pip | RedHat
  yum:
    name: python3-pip
    state: present
  when: 
    - ansible_facts['distribution'] == "RedHat"


- name: Install docker-py for docker container plugin | RedHat
  pip:
    name: docker-py
    state: present
  when: 
    - ansible_facts['distribution'] == "RedHat"